services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:case2500@db:5432/mydbimage?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads  # Mount โฟลเดอร์ uploads
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=case2500
      - POSTGRES_DB=mydbimage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: